trigger:
  branches:
    include:
      - master
      

resources:
  repositories:
    - repository: templates
      type: git
      name: Pipeline-Templates/Pipeline-Templates  
      ref: refs/heads/main

variables:
  - name: sourceBranchShort
    value: $[ split(variables['Build.SourceBranch'], '/')[sub(length(split(variables['Build.SourceBranch'], '/')), 1)] ]

stages:
  - template: master-deploy.yml@templates
    parameters:
      techStack: 'python'                                   
      appName: 'marketdata-func-0916-narasimha'              
      environmentName: 'Development'
      azureServiceConnection: 'MyAzureConnection'
      sourceBranch: '$(Build.SourceBranch)'
      sourceBranchShort: '$(sourceBranchShort)'
      sourceVersionMessage: '$(Build.SourceVersionMessage)'
      allowNonMasterDeploy: true